// <auto-generated />
using System;
using FabrikaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabrikaAPI.Migrations
{
    [DbContext(typeof(FabrikaContext))]
    [Migration("20251005153914_AddIsEmriTable")]
    partial class AddIsEmriTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FabrikaAPI.Models.IsEmri", b =>
                {
                    b.Property<int>("IsEmriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsEmriID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IsEmriKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("IsEmriID");

                    b.HasIndex("UrunID");

                    b.ToTable("IsEmirleri");

                    b.HasData(
                        new
                        {
                            IsEmriID = 1,
                            Aciklama = "ABC123 seri nolu ürünün üretimi",
                            BaslangicTarihi = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BitisTarihi = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Durum = "Tamamlandı",
                            IsEmriKodu = "WO-2024-001",
                            UrunID = 1
                        },
                        new
                        {
                            IsEmriID = 2,
                            Aciklama = "XYZ789 seri nolu ürünün üretimi",
                            BaslangicTarihi = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Durum = "Devam Ediyor",
                            IsEmriKodu = "WO-2024-002",
                            UrunID = 2
                        },
                        new
                        {
                            IsEmriID = 3,
                            Aciklama = "DEF456 seri nolu ürünün üretimi",
                            BaslangicTarihi = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Durum = "Beklemede",
                            IsEmriKodu = "WO-2024-003",
                            UrunID = 3
                        });
                });

            modelBuilder.Entity("FabrikaAPI.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Beklemede");

                    b.Property<double>("KaliteSkoru")
                        .HasColumnType("float");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UretimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("UrunID");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            UrunID = 1,
                            Durum = "Tamamlandı",
                            KaliteSkoru = 95.5,
                            SeriNo = "ABC123",
                            UretimTarihi = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 2,
                            Durum = "Üretimde",
                            KaliteSkoru = 88.700000000000003,
                            SeriNo = "XYZ789",
                            UretimTarihi = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 3,
                            Durum = "Kalite Kontrolde",
                            KaliteSkoru = 92.299999999999997,
                            SeriNo = "DEF456",
                            UretimTarihi = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 4,
                            Durum = "Tamamlandı",
                            KaliteSkoru = 97.099999999999994,
                            SeriNo = "GHI789",
                            UretimTarihi = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 5,
                            Durum = "Beklemede",
                            KaliteSkoru = 85.900000000000006,
                            SeriNo = "JKL012",
                            UretimTarihi = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FabrikaAPI.Models.IsEmri", b =>
                {
                    b.HasOne("FabrikaAPI.Models.Urun", "Urun")
                        .WithMany("IsEmirleri")
                        .HasForeignKey("UrunID");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("FabrikaAPI.Models.Urun", b =>
                {
                    b.Navigation("IsEmirleri");
                });
#pragma warning restore 612, 618
        }
    }
}
