// <auto-generated />
using System;
using FabrikaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabrikaAPI.Migrations
{
    [DbContext(typeof(FabrikaContext))]
    [Migration("20251005130005_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FabrikaAPI.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Beklemede");

                    b.Property<double>("KaliteSkoru")
                        .HasColumnType("float");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UretimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("UrunID");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            UrunID = 1,
                            Durum = "Tamamlandı",
                            KaliteSkoru = 95.5,
                            SeriNo = "ABC123",
                            UretimTarihi = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 2,
                            Durum = "Üretimde",
                            KaliteSkoru = 88.700000000000003,
                            SeriNo = "XYZ789",
                            UretimTarihi = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 3,
                            Durum = "Kalite Kontrolde",
                            KaliteSkoru = 92.299999999999997,
                            SeriNo = "DEF456",
                            UretimTarihi = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 4,
                            Durum = "Tamamlandı",
                            KaliteSkoru = 97.099999999999994,
                            SeriNo = "GHI789",
                            UretimTarihi = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UrunID = 5,
                            Durum = "Beklemede",
                            KaliteSkoru = 85.900000000000006,
                            SeriNo = "JKL012",
                            UretimTarihi = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
