// <auto-generated />
using System;
using FabrikaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabrikaAPI.Migrations
{
    [DbContext(typeof(FabrikaContext))]
    partial class FabrikaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FabrikaAPI.Models.IsEmri", b =>
                {
                    b.Property<int>("IsEmriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsEmriID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IsEmriKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("IsEmriID");

                    b.HasIndex("UrunID");

                    b.ToTable("IsEmirleri");

                    b.HasData(
                        new
                        {
                            IsEmriID = 1,
                            Aciklama = "ABC123 seri nolu ürünün üretimi",
                            BaslangicTarihi = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BitisTarihi = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Durum = "Tamamlandı",
                            IsEmriKodu = "WO-2024-001",
                            UrunID = 1
                        },
                        new
                        {
                            IsEmriID = 2,
                            Aciklama = "XYZ789 seri nolu ürünün üretimi",
                            BaslangicTarihi = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Durum = "Devam Ediyor",
                            IsEmriKodu = "WO-2024-002",
                            UrunID = 2
                        },
                        new
                        {
                            IsEmriID = 3,
                            Aciklama = "DEF456 seri nolu ürünün üretimi",
                            BaslangicTarihi = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Durum = "Beklemede",
                            IsEmriKodu = "WO-2024-003",
                            UrunID = 3
                        });
                });

            modelBuilder.Entity("FabrikaAPI.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Beklemede");

                    b.Property<double>("KaliteSkoru")
                        .HasColumnType("float");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UretimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunTipiID")
                        .HasColumnType("int");

                    b.HasKey("UrunID");

                    b.HasIndex("UrunTipiID");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            UrunID = 1,
                            Durum = "Tamamlandı",
                            KaliteSkoru = 95.5,
                            SeriNo = "ABC123",
                            UretimTarihi = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrunTipiID = 2
                        },
                        new
                        {
                            UrunID = 2,
                            Durum = "Üretimde",
                            KaliteSkoru = 88.700000000000003,
                            SeriNo = "XYZ789",
                            UretimTarihi = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrunTipiID = 1
                        },
                        new
                        {
                            UrunID = 3,
                            Durum = "Kalite Kontrolde",
                            KaliteSkoru = 92.299999999999997,
                            SeriNo = "DEF456",
                            UretimTarihi = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrunTipiID = 2
                        },
                        new
                        {
                            UrunID = 4,
                            Durum = "Tamamlandı",
                            KaliteSkoru = 97.099999999999994,
                            SeriNo = "GHI789",
                            UretimTarihi = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrunTipiID = 2
                        },
                        new
                        {
                            UrunID = 5,
                            Durum = "Beklemede",
                            KaliteSkoru = 85.900000000000006,
                            SeriNo = "JKL012",
                            UretimTarihi = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrunTipiID = 1
                        });
                });

            modelBuilder.Entity("FabrikaAPI.Models.UrunTipi", b =>
                {
                    b.Property<int>("UrunTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunTipiID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<double>("MaxKaliteSkoru")
                        .HasColumnType("float");

                    b.Property<double>("MinKaliteSkoru")
                        .HasColumnType("float");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrunKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UrunTipiID");

                    b.ToTable("UrunTipleri");

                    b.HasData(
                        new
                        {
                            UrunTipiID = 1,
                            Aciklama = "Standart A tipi ürün",
                            AktifMi = true,
                            MaxKaliteSkoru = 100.0,
                            MinKaliteSkoru = 80.0,
                            UrunAdi = "Standart Ürün A",
                            UrunKodu = "STD-A"
                        },
                        new
                        {
                            UrunTipiID = 2,
                            Aciklama = "Premium B tipi ürün",
                            AktifMi = true,
                            MaxKaliteSkoru = 100.0,
                            MinKaliteSkoru = 90.0,
                            UrunAdi = "Premium Ürün B",
                            UrunKodu = "PRE-B"
                        },
                        new
                        {
                            UrunTipiID = 3,
                            Aciklama = "Ekonomik C tipi ürün",
                            AktifMi = true,
                            MaxKaliteSkoru = 90.0,
                            MinKaliteSkoru = 70.0,
                            UrunAdi = "Ekonomik Ürün C",
                            UrunKodu = "ECO-C"
                        });
                });

            modelBuilder.Entity("FabrikaAPI.Models.IsEmri", b =>
                {
                    b.HasOne("FabrikaAPI.Models.Urun", "Urun")
                        .WithMany("IsEmirleri")
                        .HasForeignKey("UrunID");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("FabrikaAPI.Models.Urun", b =>
                {
                    b.HasOne("FabrikaAPI.Models.UrunTipi", "UrunTipi")
                        .WithMany("Urunler")
                        .HasForeignKey("UrunTipiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UrunTipi");
                });

            modelBuilder.Entity("FabrikaAPI.Models.Urun", b =>
                {
                    b.Navigation("IsEmirleri");
                });

            modelBuilder.Entity("FabrikaAPI.Models.UrunTipi", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
